### ISSUE TITLE
Max6675 not work

### ISSUE THREAD

**Issue by Drakelive** [MagoKimbra/MarlinKimbra4due#28]
Hi MagoKimbra 

With the latest Commit disappeared **HAL::spiBegin()** in  **read_max6675** function.
A question: is correct that **spiBegin** and **spiInit** are performed every time you read the temperature? (**read_max6675**)

Drakelive

**Comment by giutrec** [comment]
Hi Drakelive,
The disappared HAL::spiBegin() in read_max6675 function is not only problem for SPI work, the function `HAL::spiReceive (); `became `HAL::spiReceive (0);` and it not works with channel zero, because SPI_CHAN pin is defined according to pin SDSS ( and it is defined on boards pin config files) on pins.h.
See line later 306 and 320 on HAL.cpp
I just think it was an oversight of MagoKimbra because it was a fix already applied.
